export const search_icon = require('./MagnifyingGlass.png')
export const user_icon = require('./User.png')
export const syeong_logo = require('./Syeong.png')
export const caret_up_linear_gradient = require('./CaretUp.png')
export const map_icon = require('./MapPin.png')
export const caret_down_icon = require('./CaretDown.png')
export const caret_left_icon = require('./CaretLeft.png')
export const home_icon = require('./House.png')
export const note_icon = require('./Notepad.png')
export const fire_icon = require('./Fire.png')
export const gear_icon = require('./Gear.png')
export const pencil_icon = require('./PencilSimpleLine.png')
export const chevron_right = require('./chevron_right.png')

