export const search_icon_white = require('./MagnifyingGlass.png')
export const search_icon_gray8 = require('./MagnifyingGlass_gray8.png')
export const user_icon = require('./User.png')
export const syeong_logo = require('./Syeong.png')
export const caret_up_linear_gradient = require('./CaretUp.png')
export const map_icon = require('./MapPin.png')
export const map_icon_main3 = require('./MapPin_main3.png')
export const caret_down_icon = require('./CaretDown.png')
export const caret_left_icon = require('./CaretLeft.png')
export const caret_left_icon_white = require('./CaretLeft_white.png')
export const home_icon = require('./House.png')
export const note_icon = require('./Notepad.png')
export const fire_icon = require('./Fire.png')
export const gear_icon = require('./Gear.png')
export const pencil_icon_line = require('./PencilSimpleLine.png')
export const pencil_icon = require('./PencilSimple.png')
export const chevron_right = require('./chevron_right.png')
export const restart_icon = require('./restart_alt.png')
export const pin_icon_gray1 = require('./PushPin_gray1.png')
export const pin_icon_gray3 = require('./PushPin_gray3.png')
export const pin_icon_gray5 = require('./PushPin_gray5.png')
export const share_icon = require('./ShareNetwork.png')
export const phone_icon = require('./Phone.png')
export const clipboard_icon = require('./content_copy.png')


